"""empty message

Revision ID: 30417bc5e687
Revises: 
Create Date: 2020-11-05 23:21:23.065460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30417bc5e687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclemake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemake_name'), 'vehiclemake', ['name'], unique=False)
    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('series_code', sa.String(length=64), nullable=True),
    sa.Column('path_to_specifications', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemodel_name'), 'vehiclemodel', ['name'], unique=False)
    op.create_index(op.f('ix_vehiclemodel_path_to_specifications'), 'vehiclemodel', ['path_to_specifications'], unique=False)
    op.create_index(op.f('ix_vehiclemodel_series_code'), 'vehiclemodel', ['series_code'], unique=False)
    op.create_table('vehiclepart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('part_name', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['vehiclemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclepart_cost'), 'vehiclepart', ['cost'], unique=False)
    op.create_index(op.f('ix_vehiclepart_part_name'), 'vehiclepart', ['part_name'], unique=False)
    op.create_index(op.f('ix_vehiclepart_part_number'), 'vehiclepart', ['part_number'], unique=False)
    op.create_table('vehiclespecification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('body_style', sa.String(length=64), nullable=True),
    sa.Column('steering', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['vehiclemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclespecification_body_style'), 'vehiclespecification', ['body_style'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_engine'), 'vehiclespecification', ['engine'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_model'), 'vehiclespecification', ['model'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_name'), 'vehiclespecification', ['name'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_region'), 'vehiclespecification', ['region'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_steering'), 'vehiclespecification', ['steering'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_year'), 'vehiclespecification', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiclespecification_year'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_steering'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_region'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_name'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_model'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_engine'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_body_style'), table_name='vehiclespecification')
    op.drop_table('vehiclespecification')
    op.drop_index(op.f('ix_vehiclepart_part_number'), table_name='vehiclepart')
    op.drop_index(op.f('ix_vehiclepart_part_name'), table_name='vehiclepart')
    op.drop_index(op.f('ix_vehiclepart_cost'), table_name='vehiclepart')
    op.drop_table('vehiclepart')
    op.drop_index(op.f('ix_vehiclemodel_series_code'), table_name='vehiclemodel')
    op.drop_index(op.f('ix_vehiclemodel_path_to_specifications'), table_name='vehiclemodel')
    op.drop_index(op.f('ix_vehiclemodel_name'), table_name='vehiclemodel')
    op.drop_table('vehiclemodel')
    op.drop_index(op.f('ix_vehiclemake_name'), table_name='vehiclemake')
    op.drop_table('vehiclemake')
    # ### end Alembic commands ###
