"""empty message

Revision ID: 4a4cfd1e0461
Revises: 
Create Date: 2020-11-12 14:49:24.333495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4cfd1e0461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclemake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiclemake'))
    )
    with op.batch_alter_table('vehiclemake', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiclemake_name'), ['name'], unique=False)

    op.create_table('vehiclesystemparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=64), nullable=True),
    sa.Column('class_element', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiclesystemparts'))
    )
    with op.batch_alter_table('vehiclesystemparts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiclesystemparts_class_element'), ['class_element'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclesystemparts_system'), ['system'], unique=False)

    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('series_code', sa.String(length=64), nullable=True),
    sa.Column('path_to_specifications', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], name=op.f('fk_vehiclemodel_make_id_vehiclemake')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiclemodel'))
    )
    with op.batch_alter_table('vehiclemodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiclemodel_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclemodel_path_to_specifications'), ['path_to_specifications'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclemodel_series_code'), ['series_code'], unique=False)

    op.create_table('vehiclespecification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('destination_region', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('body_style', sa.String(length=64), nullable=True),
    sa.Column('steering', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('model_year_from', sa.String(length=64), nullable=True),
    sa.Column('model_year_to', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('transmission', sa.String(length=64), nullable=True),
    sa.Column('series_description', sa.String(length=64), nullable=True),
    sa.Column('path_to_partscatalog', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], name=op.f('fk_vehiclespecification_make_id_vehiclemake')),
    sa.ForeignKeyConstraint(['model_id'], ['vehiclemodel.id'], name=op.f('fk_vehiclespecification_model_id_vehiclemodel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiclespecification'))
    )
    with op.batch_alter_table('vehiclespecification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiclespecification_body_style'), ['body_style'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_destination_region'), ['destination_region'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_engine'), ['engine'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_model_year_from'), ['model_year_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_model_year_to'), ['model_year_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_path_to_partscatalog'), ['path_to_partscatalog'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_series_description'), ['series_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_steering'), ['steering'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_transmission'), ['transmission'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclespecification_year'), ['year'], unique=False)

    op.create_table('vehiclepart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_category', sa.String(length=64), nullable=True),
    sa.Column('part_subcategory', sa.String(length=64), nullable=True),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('part_name', sa.String(length=64), nullable=True),
    sa.Column('part_code', sa.String(length=64), nullable=True),
    sa.Column('qty_required', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.Column('manufacturer_note', sa.String(length=64), nullable=True),
    sa.Column('end_of_production', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('associated_parts', sa.String(length=64), nullable=True),
    sa.Column('path_to_cost', sa.Text(), nullable=True),
    sa.Column('cost', sa.String(length=64), nullable=True),
    sa.Column('specification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specification_id'], ['vehiclespecification.id'], name=op.f('fk_vehiclepart_specification_id_vehiclespecification')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiclepart'))
    )
    with op.batch_alter_table('vehiclepart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiclepart_associated_parts'), ['associated_parts'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_comment'), ['comment'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_end_of_production'), ['end_of_production'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_manufacturer_note'), ['manufacturer_note'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_note'), ['note'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_part_category'), ['part_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_part_code'), ['part_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_part_name'), ['part_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_part_subcategory'), ['part_subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_path_to_cost'), ['path_to_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclepart_qty_required'), ['qty_required'], unique=False)

    op.create_table('vehiclesystemdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('subsystem', sa.String(length=64), nullable=True),
    sa.Column('path_to_parts', sa.Text(), nullable=True),
    sa.Column('specification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specification_id'], ['vehiclespecification.id'], name=op.f('fk_vehiclesystemdetails_specification_id_vehiclespecification')),
    sa.ForeignKeyConstraint(['system_id'], ['vehiclesystemparts.id'], name=op.f('fk_vehiclesystemdetails_system_id_vehiclesystemparts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiclesystemdetails'))
    )
    with op.batch_alter_table('vehiclesystemdetails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiclesystemdetails_path_to_parts'), ['path_to_parts'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiclesystemdetails_subsystem'), ['subsystem'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiclesystemdetails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiclesystemdetails_subsystem'))
        batch_op.drop_index(batch_op.f('ix_vehiclesystemdetails_path_to_parts'))

    op.drop_table('vehiclesystemdetails')
    with op.batch_alter_table('vehiclepart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiclepart_qty_required'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_path_to_cost'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_part_subcategory'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_part_number'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_part_name'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_part_code'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_part_category'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_note'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_manufacturer_note'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_end_of_production'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_cost'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_comment'))
        batch_op.drop_index(batch_op.f('ix_vehiclepart_associated_parts'))

    op.drop_table('vehiclepart')
    with op.batch_alter_table('vehiclespecification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_year'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_transmission'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_steering'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_series_description'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_path_to_partscatalog'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_name'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_model_year_to'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_model_year_from'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_model'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_market'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_grade'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_engine'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_destination_region'))
        batch_op.drop_index(batch_op.f('ix_vehiclespecification_body_style'))

    op.drop_table('vehiclespecification')
    with op.batch_alter_table('vehiclemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiclemodel_series_code'))
        batch_op.drop_index(batch_op.f('ix_vehiclemodel_path_to_specifications'))
        batch_op.drop_index(batch_op.f('ix_vehiclemodel_name'))

    op.drop_table('vehiclemodel')
    with op.batch_alter_table('vehiclesystemparts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiclesystemparts_system'))
        batch_op.drop_index(batch_op.f('ix_vehiclesystemparts_class_element'))

    op.drop_table('vehiclesystemparts')
    with op.batch_alter_table('vehiclemake', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiclemake_name'))

    op.drop_table('vehiclemake')
    # ### end Alembic commands ###
