"""empty message

Revision ID: b22bd484cdd0
Revises: 
Create Date: 2020-11-03 16:53:38.395579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22bd484cdd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclemake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemake_name'), 'vehiclemake', ['name'], unique=False)
    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemodel_name'), 'vehiclemodel', ['name'], unique=False)
    op.create_index(op.f('ix_vehiclemodel_series'), 'vehiclemodel', ['series'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiclemodel_series'), table_name='vehiclemodel')
    op.drop_index(op.f('ix_vehiclemodel_name'), table_name='vehiclemodel')
    op.drop_table('vehiclemodel')
    op.drop_index(op.f('ix_vehiclemake_name'), table_name='vehiclemake')
    op.drop_table('vehiclemake')
    # ### end Alembic commands ###
