"""empty message

Revision ID: cec89c9c4ff1
Revises: 
Create Date: 2020-11-07 15:31:31.293004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec89c9c4ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclemake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemake_name'), 'vehiclemake', ['name'], unique=False)
    op.create_table('vehiclesystem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=64), nullable=True),
    sa.Column('class_element', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclesystem_class_element'), 'vehiclesystem', ['class_element'], unique=False)
    op.create_index(op.f('ix_vehiclesystem_system'), 'vehiclesystem', ['system'], unique=False)
    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('series_code', sa.String(length=64), nullable=True),
    sa.Column('path_to_specifications', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemodel_name'), 'vehiclemodel', ['name'], unique=False)
    op.create_index(op.f('ix_vehiclemodel_path_to_specifications'), 'vehiclemodel', ['path_to_specifications'], unique=False)
    op.create_index(op.f('ix_vehiclemodel_series_code'), 'vehiclemodel', ['series_code'], unique=False)
    op.create_table('vehiclesubsystem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsystem', sa.String(length=64), nullable=True),
    sa.Column('path_to_parts', sa.String(length=64), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['vehiclesystem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclesubsystem_path_to_parts'), 'vehiclesubsystem', ['path_to_parts'], unique=False)
    op.create_index(op.f('ix_vehiclesubsystem_subsystem'), 'vehiclesubsystem', ['subsystem'], unique=False)
    op.create_table('vehiclesecondlevelsubsystem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secondlevel_subsystem', sa.String(length=64), nullable=True),
    sa.Column('path_to_parts', sa.String(length=64), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('subsystem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subsystem_id'], ['vehiclesubsystem.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['vehiclesystem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclesecondlevelsubsystem_path_to_parts'), 'vehiclesecondlevelsubsystem', ['path_to_parts'], unique=False)
    op.create_index(op.f('ix_vehiclesecondlevelsubsystem_secondlevel_subsystem'), 'vehiclesecondlevelsubsystem', ['secondlevel_subsystem'], unique=False)
    op.create_table('vehiclespecification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('destination_region', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('body_style', sa.String(length=64), nullable=True),
    sa.Column('steering', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('model_year_from', sa.String(length=64), nullable=True),
    sa.Column('model_year_to', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('transmission', sa.String(length=64), nullable=True),
    sa.Column('series_description', sa.String(length=64), nullable=True),
    sa.Column('path_to_partscatalog', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['vehiclemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclespecification_body_style'), 'vehiclespecification', ['body_style'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_destination_region'), 'vehiclespecification', ['destination_region'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_engine'), 'vehiclespecification', ['engine'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_grade'), 'vehiclespecification', ['grade'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_market'), 'vehiclespecification', ['market'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_model'), 'vehiclespecification', ['model'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_model_year_from'), 'vehiclespecification', ['model_year_from'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_model_year_to'), 'vehiclespecification', ['model_year_to'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_name'), 'vehiclespecification', ['name'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_path_to_partscatalog'), 'vehiclespecification', ['path_to_partscatalog'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_series_description'), 'vehiclespecification', ['series_description'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_steering'), 'vehiclespecification', ['steering'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_transmission'), 'vehiclespecification', ['transmission'], unique=False)
    op.create_index(op.f('ix_vehiclespecification_year'), 'vehiclespecification', ['year'], unique=False)
    op.create_table('vehicle3rdlevelsubsystem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thirdlevel_subsystem', sa.String(length=64), nullable=True),
    sa.Column('path_to_parts', sa.String(length=64), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('subsystem_id', sa.Integer(), nullable=True),
    sa.Column('secondlevel_subsystem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secondlevel_subsystem_id'], ['vehiclesecondlevelsubsystem.id'], ),
    sa.ForeignKeyConstraint(['subsystem_id'], ['vehiclesubsystem.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['vehiclesystem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle3rdlevelsubsystem_path_to_parts'), 'vehicle3rdlevelsubsystem', ['path_to_parts'], unique=False)
    op.create_index(op.f('ix_vehicle3rdlevelsubsystem_thirdlevel_subsystem'), 'vehicle3rdlevelsubsystem', ['thirdlevel_subsystem'], unique=False)
    op.create_table('vehiclepart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('part_name', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.String(length=64), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('subsystem_id', sa.Integer(), nullable=True),
    sa.Column('secondlevel_subsystem_id', sa.Integer(), nullable=True),
    sa.Column('thirdlevel_subsystem_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehiclemake.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['vehiclemodel.id'], ),
    sa.ForeignKeyConstraint(['secondlevel_subsystem_id'], ['vehiclesecondlevelsubsystem.id'], ),
    sa.ForeignKeyConstraint(['subsystem_id'], ['vehiclesubsystem.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['vehiclesystem.id'], ),
    sa.ForeignKeyConstraint(['thirdlevel_subsystem_id'], ['vehicle3rdlevelsubsystem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclepart_cost'), 'vehiclepart', ['cost'], unique=False)
    op.create_index(op.f('ix_vehiclepart_part_name'), 'vehiclepart', ['part_name'], unique=False)
    op.create_index(op.f('ix_vehiclepart_part_number'), 'vehiclepart', ['part_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiclepart_part_number'), table_name='vehiclepart')
    op.drop_index(op.f('ix_vehiclepart_part_name'), table_name='vehiclepart')
    op.drop_index(op.f('ix_vehiclepart_cost'), table_name='vehiclepart')
    op.drop_table('vehiclepart')
    op.drop_index(op.f('ix_vehicle3rdlevelsubsystem_thirdlevel_subsystem'), table_name='vehicle3rdlevelsubsystem')
    op.drop_index(op.f('ix_vehicle3rdlevelsubsystem_path_to_parts'), table_name='vehicle3rdlevelsubsystem')
    op.drop_table('vehicle3rdlevelsubsystem')
    op.drop_index(op.f('ix_vehiclespecification_year'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_transmission'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_steering'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_series_description'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_path_to_partscatalog'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_name'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_model_year_to'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_model_year_from'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_model'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_market'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_grade'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_engine'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_destination_region'), table_name='vehiclespecification')
    op.drop_index(op.f('ix_vehiclespecification_body_style'), table_name='vehiclespecification')
    op.drop_table('vehiclespecification')
    op.drop_index(op.f('ix_vehiclesecondlevelsubsystem_secondlevel_subsystem'), table_name='vehiclesecondlevelsubsystem')
    op.drop_index(op.f('ix_vehiclesecondlevelsubsystem_path_to_parts'), table_name='vehiclesecondlevelsubsystem')
    op.drop_table('vehiclesecondlevelsubsystem')
    op.drop_index(op.f('ix_vehiclesubsystem_subsystem'), table_name='vehiclesubsystem')
    op.drop_index(op.f('ix_vehiclesubsystem_path_to_parts'), table_name='vehiclesubsystem')
    op.drop_table('vehiclesubsystem')
    op.drop_index(op.f('ix_vehiclemodel_series_code'), table_name='vehiclemodel')
    op.drop_index(op.f('ix_vehiclemodel_path_to_specifications'), table_name='vehiclemodel')
    op.drop_index(op.f('ix_vehiclemodel_name'), table_name='vehiclemodel')
    op.drop_table('vehiclemodel')
    op.drop_index(op.f('ix_vehiclesystem_system'), table_name='vehiclesystem')
    op.drop_index(op.f('ix_vehiclesystem_class_element'), table_name='vehiclesystem')
    op.drop_table('vehiclesystem')
    op.drop_index(op.f('ix_vehiclemake_name'), table_name='vehiclemake')
    op.drop_table('vehiclemake')
    # ### end Alembic commands ###
